# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  format_listener:
    enabled: true
    rules:
    - { path: '^/api/*', priorities: ['json'], fallback_format: 'json' }
  view:
    view_response_listener: true
    mime_types:
      json: ['application/json;charset=UTF-8', 'application/json']

  exception:
    exception_controller: 'fos_rest.exception.controller:showAction'
    messages:
      'App\Exception\InvalidDataException': true