jms_serializer:
  visitors:
    xml_serialization:
      format_output: '%kernel.debug%'
    json_serialization:
      options: [JSON_UNESCAPED_SLASHES, JSON_PRESERVE_ZERO_FRACTION] #[JSON_UNESCAPED_SLASHES, JSON_UNESCAPED_UNICODE]
  metadata:
    directories:
      Entity:
        namespace_prefix: 'App\Entity'
        path: "%kernel.project_dir%/serializer/Entity"
