security:
  encoders:
    App\Entity\Account:
      algorithm: bcrypt

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Account
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern:  ^/api/login
      stateless: true
      anonymous: true
      json_login:
        check_path: /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    register:
      pattern: ^/api/register
      stateless: true
      anonymous: true

    post:
      pattern: ^/api/post
      methods: [GET]
      stateless: true
      anonymous: true

    homepage:
      pattern: ^/api/homepage
      methods: [GET]
      stateless: true
      anonymous: true

    categories:
      pattern: ^/api/categories
      methods: [GET]
      stateless: true
      anonymous: true

    main:
      stateless: true
      anonymous: false
      provider: app_user_provider
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control: